/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith("org.jetbrains.kotlin")) {
                gradle.rootProject.extra["kotlinVersion"]?.let { useVersion(it as String) }
            }
        }
    }
}

rootProject.name = "ecommerce-api"

fun module(name: String) {
    include(name)
    project(":$name").projectDir = file(name)
}

module("ecommerce-api-core")
module("ecommerce-api-endpoint")
module("ecommerce-api-common")
