/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ramusthastudio.ecommerce.java-conventions")
    kotlin("jvm")
}

description = "ecommerce-api-common"
version = "0.0.1-SNAPSHOT"
