/*
 * This file was generated by the Gradle 'init' task.
 */

val ktorVersion: String by project

plugins {
    id("com.ramusthastudio.ecommerce.java-conventions")
    kotlin("jvm")
    kotlin("plugin.serialization")
}

description = "ecommerce-api-common"
version = "0.0.1-SNAPSHOT"

dependencies {
    api("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
}
