/*
 * This file was generated by the Gradle 'init' task.
 */

val slf4jApiVersion: String by project
val logbackClassicVersion: String by project
val junitJupiterVersion: String by project
val hamcrestVersion: String by project

plugins {
    `java-library`
    `maven-publish`
}

group = "com.ramusthastudio.ecommerce"
version = "0.0.1-SNAPSHOT"

repositories {
    gradlePluginPortal()
    mavenCentral()
    mavenLocal()
    maven("https://repo.maven.apache.org/maven2/")
    maven("https://maven.pkg.jetbrains.space/public/p/ktor/eap")
}

dependencies {
    api("org.slf4j:slf4j-api:$slf4jApiVersion")
    api("ch.qos.logback:logback-classic:$logbackClassicVersion")

    testImplementation(kotlin("test"))
    testImplementation("org.junit.jupiter:junit-jupiter:$junitJupiterVersion")
    testImplementation("org.hamcrest:hamcrest:$hamcrestVersion")
}

tasks.test {
    useJUnitPlatform()
}

java.sourceCompatibility = JavaVersion.VERSION_17

sourceSets.main {
    java.srcDirs("src/main/java", "src/main/kotlin")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
