import org.jetbrains.kotlin.gradle.plugin.KotlinTargetHierarchy.SourceSetTree.Companion.test

/*
 * This file was generated by the Gradle 'init' task.
 */

val ktorVersion: String by project

plugins {
    application
    id("com.ramusthastudio.ecommerce.java-conventions")
    kotlin("jvm")
    kotlin("plugin.serialization")
}

application {
    mainClass.set("com.ramusthastudio.ecommerce.outbound.EcommerceApi.kt")
}

description = "ecommerce-api-endpoint"
version = "0.0.1-SNAPSHOT"

dependencies {
    api(project(":ecommerce-api-core"))

    api("io.ktor:ktor-server-cio:$ktorVersion")
    api("io.ktor:ktor-server-core:$ktorVersion")
    api("io.ktor:ktor-server-content-negotiation:$ktorVersion")
    api("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
    testImplementation("io.ktor:ktor-server-test-host:$ktorVersion")
}

tasks {
    create("stage").dependsOn("installDist")

    test {
        enabled = false
    }
}
