/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ramusthastudio.ecommerce.java-conventions")
    kotlin("jvm")
}

description = "ecommerce-api-endpoint"
version = "0.0.1-SNAPSHOT"

dependencies {
    api("io.ktor:ktor-client-cio-jvm:2.3.4")
    api("io.ktor:ktor-client-core-jvm:2.3.4")
    api("io.ktor:ktor-client-content-negotiation-jvm:2.3.4")
    api("io.ktor:ktor-serialization-kotlinx-json-jvm:2.3.4")
    api("io.ktor:ktor-client-logging-jvm:2.3.4")
    api(project(":ecommerce-api-common"))
    api("org.slf4j:slf4j-api:2.0.7")
    api("ch.qos.logback:logback-classic:1.4.9")
}
